services:
  - type: web
    name: api-solucoes-urbanas
    env: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_LEVEL
        value: error
